# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

User.create(:username => "Vikko", :email => "vikko@awesomesc2.com", :password => "password", :password_confirmation => "password")
User.create(:username => "Maran", :email => "maran.hidskes@gmail.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test1", :email => "test1@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test2", :email => "test2@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test3", :email => "test3@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test4", :email => "test4@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test5", :email => "test5@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test6", :email => "test6@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test7", :email => "test7@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test8", :email => "test8@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test9", :email => "test9@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test10", :email => "test10@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test11", :email => "test11@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test12", :email => "test12@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test13", :email => "test13@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test14", :email => "test14@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test15", :email => "test15@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test16", :email => "test16@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test17", :email => "test17@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test18", :email => "test18@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test19", :email => "test19@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test20", :email => "test20@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test21", :email => "test21@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test22", :email => "test22@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test23", :email => "test23@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test24", :email => "test24@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")
User.create(:username => "Test25", :email => "test25@awesomesc2.com", :password => "ilovesc2", :password_confirmation => "ilovesc2")